### ISSUE TITLE
UE5.6 Metahuman Creator DCC Export Issue

### ISSUE THREAD

**Issue by SunRicardo** [poly-hammer/meta-human-dna-addon#147]
I have discovered that in the current version of UE5.6, when using DCC to export MHC, there are issues with the base color texture mapping.

<img width="2198" height="1104" alt="Image" src="https://github.com/user-attachments/assets/8d26919b-1c1d-49be-a61b-d2bae10071e4" />
This is the texture exported from DCC. As you can see, there are issues with the two base color textures. The face texture is more similar to the original texture of MH rather than my custom texture. The body texture also has significant problems; the color is no longer a realistic skin color.

———————————————————————————————————————↓↓↓↓↓↓↓↓↓↓
<img width="2198" height="1104" alt="Image" src="https://github.com/user-attachments/assets/46b1d4a8-12e3-4683-8b78-1bc1c72452c8" />

<img width="788" height="393" alt="Image" src="https://github.com/user-attachments/assets/6722cca0-7d53-4091-a0ff-2eaf55fbf16d" />

<img width="3354" height="549" alt="Image" src="https://github.com/user-attachments/assets/a5f4fc4c-23a4-4bc1-9f5f-c515c0b11b37" />

<img width="1137" height="414" alt="Image" src="https://github.com/user-attachments/assets/8ced2031-01d6-473e-b39b-225652a34d1f" />

Therefore, I manually replaced the two base color textures before using the DNA Addon, and then imported the MH DNA into Blender.Because when exporting directly from MHC to UE, there were no issues with the textures. Therefore, I replaced them with the textures located in the MH folder within UE, including 2 base color textures and the 3 base color animation texture for the face.

———————————————————————————————————————↓↓↓↓↓↓↓↓↓↓

<img width="3171" height="1341" alt="Image" src="https://github.com/user-attachments/assets/a139cc0c-bc1a-4a16-9f69-e7c819748ce8" />
By default, this is fine.

<img width="3165" height="1347" alt="Image" src="https://github.com/user-attachments/assets/23e62f33-7bc5-4828-a13c-fc8116c64837" />

<img width="3168" height="1326" alt="Image" src="https://github.com/user-attachments/assets/1d4f1f43-6e6e-4ab4-a491-a517b3b49267" />
However, after the test, it can be seen that there are some issues with the base color animation texture.

———————————————————————————————————————↓↓↓↓↓↓↓↓↓↓

<img width="2198" height="1104" alt="Image" src="https://github.com/user-attachments/assets/3777c819-143d-4704-b4e5-1790bb7c5ab2" />

<img width="960" height="362" alt="Image" src="https://github.com/user-attachments/assets/e3f56aa0-9f8e-4140-846f-aca3a3077b24" />
Because the MH texture exported by DCC is different from the one directly imported into UE, I'm not quite sure about the specific reason, nor am I sure if my operation is correct, nor do I know if this is a bug of MHC? Is this a bug of MHC? It's uncertain when this issue will be fixed by Epic. Are there any good solutions to this problem at present? Because MH textures in UE cannot be directly replaced; only replacing the body textures without replacing the facial textures results in seams at the neck area.

**Comment by SunRicardo** [comment]
<img width="656" height="585" alt="Image" src="https://github.com/user-attachments/assets/93fd1924-3d6c-4ef8-b43b-5cf495ecdec1" />
I used my own textures in MHC, and everything worked fine in MHC and UE. Could this be a bug in the DCC export?

**Comment by jack-yao91** [comment]
Yea there is some weirdness with how the textures do the DCC export in 5.6, like for instance there is a body cavity map, but none for the head. But when looking at it one could assume `Chest_Cavity.png` is what should be `Head_Cavity.png`.

Also this happens with the 5.6 textures from DCC export now:
https://github.com/poly-hammer/meta-human-dna-addon/issues/145

So this might be something the material graph can be edited to work around, or maybe the import process can extract new image data. However, any information/observations/findings people can post here about this is appreciated.

**Comment by jack-yao91** [comment]
Apparently the Unreal 5.6.1 release that just went out had some fixes to MetaHuman Creator. There were some texture export related fixes, I don't know if it was specifically this, but it was in their release notes

**Comment by SunRicardo** [comment]
> Apparently the Unreal 5.6.1 release that just went out had some fixes to MetaHuman Creator. There were some texture export related fixes, I don't know if it was specifically this, but it was in their release notes

OK, thank you for the new information. I'm on a business trip right now. After I get home next week, I'll test it out. This is really exciting!

**Comment by jack-yao91** [comment]
Merged these issues into this one:
https://github.com/poly-hammer/meta-human-dna-addon/issues/154
https://github.com/poly-hammer/meta-human-dna-addon/issues/162

Since these are related to issues with MetaHuman Creator. Here is a link to fill out an Unreal bug report if someone would like to report this issue.
https://www.unrealengine.com/en-US/support/report-a-bug

For now though, this issue lets people share information about this and monitor the issue till it is fixed, but isn't something that we can fix from the blender addon side of things.

**Comment by aetheraeimofficial** [comment]
found a fix but this didnt fix the eye problem. 

https://forums.unrealengine.com/t/i-downloaded-a-metahuman-with-8k-textures-in-unreal-engine-5-6-but-in-the-texture-folder-it-only-shows-2k-textures-where-can-i-find-the-8k-face-texture/2600854/2

textures are exporting at 8k now except the eyes which I dont mind.
