### ISSUE TITLE
Add support for Mac x86_64

### ISSUE THREAD

**Issue by max-sho** [poly-hammer/meta-human-dna-addon#72]
Using Blender 4.2 and 4.3. on Mac OS 

After installing .zip package into blender add-on is not working as intended. 

<img width="223" alt="Image" src="https://github.com/user-attachments/assets/e9f6b068-8d54-4b0f-8a52-2364053fa4ea" />

**Comment by jack-yao91** [comment]
Looks like you installed only the addon code instead of the final compiled version.

Due to liscencing constraints we cant ship the compiled dependencies directly so we made this tool to help you compile them yourself.

https://www.youtube.com/watch?v=BAyCV8GwmCM

Following this should show you how to make your own release. Then install it, and this should be fixed.

**Comment by max-sho** [comment]
I followed the instructions and successfully complied the zip file i retried the steps a couple of times and the result still persists...

I'm not sure how to resolve this?

**Comment by jack-yao91** [comment]
Ok I think I know what happened and we did a fix. Can you re-run the build tool one more time and let me know if that works? Also this is a Mac with the M series chips correct?

**Comment by max-sho** [comment]
No this is intel series

**Comment by jack-yao91** [comment]
Ok, currently we don't have support for that. It's something we might be able to add in the future though, so I'll keep this open as a feature for Mac intel arch support
